### ISSUE TITLE
Add support for PostgreSQL

### ISSUE THREAD

**Issue by mvysny** [mvysny/jdbi-orm-vaadin-crud-demo#29]
Add support for PostgreSQL:

1. Add pgsql jdbc driver as a dependency
2. Allow for specifying JDBC_URL, JDBC_USERNAME, JDBC_PASSWORD as env variables

This is to demo the app running in Kubernetes or Docker-compose, with a permanent database.

**Comment by mvysny** [comment]
Add `docker-compose.yaml` or kubernetes yaml file + document how to run the app persistently in kubernetes.

**Comment by mvysny** [comment]
Support for docker-compose added, however the app starts too fast and then fails because the database is not yet up:
```
web_1       | org.postgresql.util.PSQLException: Connection to postgres:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
web_1       | 	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
web_1       | 	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
web_1       | 	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
web_1       | 	at org.postgresql.Driver.makeConnection(Driver.java:434)
web_1       | 	at org.postgresql.Driver.connect(Driver.java:291)
web_1       | 	at com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
web_1       | 	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:359)
web_1       | 	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:201)
web_1       | 	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:470)
web_1       | 	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:561)
web_1       | 	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:100)
web_1       | 	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
web_1       | 	at com.vaadin.starter.skeleton.Bootstrap.contextInitialized(Bootstrap.java:54)
```
Perhaps HikariCP can be configured to backoff+retry automatically for a couple of seconds?

**Comment by mvysny** [comment]
Trying `hikariConfig.setInitializationFailTimeout()` - it worked!
